# Generated by Django 6.0.3 on 2026-03-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='avg_bp',
            field=models.CharField(blank=True, help_text='e.g., 120/80 mmHg', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='pulse_bpm',
            field=models.IntegerField(blank=True, help_text='Pulse rate in bpm', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session_notes',
            field=models.TextField(blank=True, help_text="Therapist's clinical notes for this session", null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='weight_kg',
            field=models.FloatField(blank=True, help_text='Patient weight in kg', null=True),
        ),
    ]
