# Generated by Django 6.0.3 on 2026-03-22 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendance_avg_bp_attendance_pulse_bpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentcycle',
            name='is_cancelled_midway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='detailed_info',
            field=models.TextField(blank=True, help_text='In-depth point-wise explanation of the treatment for patients'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
