# Generated by Django 6.0.5 on 2026-07-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_treatmentcycle_is_cancelled_midway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentcycle',
            name='ai_report_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentcycle',
            name='ai_report_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
